#! /user/bin/env bash

GREETING=HI
STATEMENT="My name is,"
INTERROGATIVEPRONOUN1=what?
INTERROGATIVEPRONOUN2=who?
NAME=${1:-"Slim Shady"}
ALLITERATION=chka-chka

echo ${STATEMENT} ${INTERROGATIVEPRONOUN1}
echo ${STATEMENT} ${INTERROGATIVEPRONOUN2}
echo ${STATEMENT} ${ALLITERATION} ${NAME}